const mongoose = require("mongoose");

// A roster entry is one candidate's authorized slot for THE exam — NEET is
// one single exam with four sections (Physics, Chemistry, Botany, Zoology),
// not four separate exams a candidate picks one of. There is no per-subject
// registration; a candidate registers once, for the one exam, full stop.
//
// This is no longer pre-loaded by an institution either — there usually
// isn't one. NEET-style open exams draw from droppers, repeaters, and
// students across thousands of schools with no single list anyone holds.
// The roster entry is created automatically the moment a candidate completes
// self-registration; rollNumber is generated by the system, not known in
// advance by anybody.
const rosterSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, lowercase: true, trim: true },

    // The real uniqueness anchor. Email alone was always trivially defeatable
    // (anyone can make a second Gmail address) — a government ID number is a
    // meaningfully higher barrier to registering twice. idType makes the
    // format unambiguous and consistent — without it, one candidate's number
    // might be Aadhaar, another's a driving license, and the system has no
    // way to validate either or even tell them apart. v1 only ACCEPTS
    // Aadhaar (see idType enum) but the field exists now so adding PAN/Voter
    // ID/DL later is a config change, not a schema migration.
    //
    // governmentId is stored normalized (no spaces/dashes) and is checked at
    // registration for correct length + the Verhoeff checksum real Aadhaar
    // numbers satisfy (see src/utils/aadhaarValidator.js). This does NOT
    // verify the number actually belongs to the registrant or is a real,
    // issued number — that requires a live government API call, explicitly
    // deferred to v2. It does close the "type any random string" gap.
    idType: { type: String, enum: ["aadhaar"], default: "aadhaar" },
    governmentId: { type: String, required: true, trim: true },

    rollNumber: { type: String, required: true, trim: true, unique: true },

    claimed: { type: Boolean, default: false },
    claimedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    claimedAt: { type: Date, default: null },

    // ── Exam Access Code ──────────────────────────────────────────────────
    // One code per candidate for the one exam sitting — real exam centers
    // ban personal devices, so OTP-over-email cannot work as the exam-day
    // gate. This code is generated in advance and typed once by the
    // candidate at the center, no live network round-trip to their phone
    // required.
    examCode: { type: String, default: null }, // 8-char, set when generated
    examCodeWindowStart: { type: Date, default: null },
    examCodeWindowEnd: { type: Date, default: null },
    examCodeUsed: { type: Boolean, default: false },
    examCodeUsedAt: { type: Date, default: null },
    // Captured but not enforced in v1 — lays groundwork for IP-binding once
    // centers with fixed network ranges can be onboarded.
    examCodeUsedFromIp: { type: String, default: null },
  },
  { timestamps: true }
);

// Both anchors must be globally unique — there's only one exam, so no
// per-subject scoping anymore. Re-registering with a new email but the same
// government ID is blocked by the governmentId index; re-registering with
// the same email is blocked by the email index.
rosterSchema.index({ email: 1 }, { unique: true });
rosterSchema.index({ governmentId: 1 }, { unique: true });

// Generates an 8-character exam access code, excluding visually ambiguous
// characters (0/O, 1/I/L) since this gets typed under time pressure on a
// center machine, often read off a printed slip rather than copy-pasted.
const CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
rosterSchema.statics.generateCode = function () {
  let code = "";
  for (let i = 0; i < 8; i++) {
    code += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)];
  }
  return code;
};

// Generates a human-readable roll number: year + sequential count. No
// subject prefix anymore — there's one exam, not four, so a roll number
// doesn't need to encode which "track" a candidate is on.
//
// NOTE: count-then-increment has a race window under concurrent registrations
// — two candidates registering in the same instant could compute the same
// next number. The unique index above will correctly reject the second
// write rather than silently issuing a duplicate roll number, but the caller
// (auth.js) needs to catch that specific error and retry generation rather
// than surfacing a raw 500 to the candidate. Acceptable at v1 volume; a
// proper fix would use an atomic counter document if registration traffic
// ever gets heavy enough for collisions to become common rather than rare.
rosterSchema.statics.generateRollNumber = async function () {
  const year = new Date().getFullYear().toString().slice(-2);
  const prefix = `NEET${year}`;

  const count = await this.countDocuments({
    rollNumber: { $regex: `^${prefix}` },
  });

  const sequence = (count + 1).toString().padStart(6, "0");
  return `${prefix}${sequence}`;
};

module.exports = mongoose.model("Roster", rosterSchema);
